import Header from "./components/Header";
import "./globals.css";
import { Poppins } from "next/font/google";
import Head from 'next/head';

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "600"] });
import 'react-toastify/dist/ReactToastify.css'; // Import the CSS
import { ToastContainer } from 'react-toastify';


export const metadata = {
    title: "Todo App",
    description: "Generated by create next app",
    image: "/favicon.ico"
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <Head>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <body className={poppins.className}>
                <Header />
                <main>{children}</main>
                <ToastContainer />
            </body>
        </html>
    );
}
